#!/usr/bin/perl -w

# This is meant to suppress these annoying "subroutine redefined" warnings
no warnings "redefine";

use strict;

use CGI;

use Technion::Seminars::Config;
use Technion::Seminars::Layout;
use Technion::Seminars::SlashUrl;
use Technion::Seminars::DBI;
use Technion::Seminars::TypeMan;

use Gamla::TextStream::Out::File;

use POSIX qw(strftime);

use Time::DaysInMonth;

my $q = CGI->new();

my ($year, $month, $day);

sub check_url
{
    my $url = shift;

    my $verdict = ($url =~ /^day\/(\d{4})\/(0[1-9]|1[0-2])\/(0[1-9]|[1-2][0-9]|3[0-1])\/$/) ? 1 : 0;

    if ($verdict)
    {

        ($year,$month,$day) = ($1,$2,$3);

        if ($day > days_in($year, $month))
        {
            $verdict = 0;
        }
    }
    
    return ($verdict, strftime("day/%Y/%m/%d/", localtime(time())));
}

# Make sure our URL ends with a slash.
my $base_url = &normalize_url($q, \&check_url);

print $q->header();

use vars qw($title);
$title = "Daily Calendar";

my $layout = 
    Technion::Seminars::Layout->new(
        'path' => $base_url,
        'title' => $title,
    );

my $o = Gamla::TextStream::Out::File->new(\*STDOUT);

sub draw_page
{
    my $o = shift;

    $o->print("<h1>$title</h1>\n");

    my $dbh = Technion::Seminars::DBI->new();

    my $sth = $dbh->prepare("SELECT seminars.Seminar_ID, seminars.Title, seminars.Time FROM seminars WHERE seminars.Date = " . $dbh->quote(sprintf("%.4i-%.2i-%.2i", $year,$month,$day)) . " ORDER BY seminars.Time");

    my $rv = $sth->execute();

    my $this_time = strftime("%k:%M:%S", localtime(time()));

    my $type_man = Technion::Seminars::TypeMan::get_type_man();

    while (my $row = $sth->fetchrow_arrayref())
    {
        my ($seminar_id, $title, $time) = @$row;

        my $before = $type_man->compare_values("time", "", $time, $this_time);

        my $class = ($before < 0) ? "after" : "before";

        $o->print("<p><b class=\"$class\">$time</b>: <a href=\"../../../../seminar/$seminar_id/\" class=\"$class\">" . CGI::escapeHTML($title) . "</a></p>");        
    }

}







$layout->render($o, \&draw_page);
