#!/usr/bin/perl -w

# This is meant to suppress these annoying "subroutine redefined" warnings
no warnings "redefine";

use strict;

use CGI;

use Technion::Seminars::Config;
use Technion::Seminars::Layout;
use Technion::Seminars::SlashUrl;

use Gamla::TextStream::Out::File;

use POSIX qw(strftime);

use Time::DaysInMonth;

my $q = CGI->new();

sub check_url
{
    my $url = shift;

    my $verdict = ($url =~ /^day\/(\d{4})\/(0[1-9]|1[0-2])\/(0[1-9]|[1-2][0-9]|3[0-1])\/$/) ? 1 : 0;

    if ($verdict)
    {

        my ($y,$m,$d) = ($1,$2,$3);

        if ($d > days_in($y, $m))
        {
            $verdict = 0;
        }
    }
    
    return ($verdict, strftime("day/%Y/%m/%d/", localtime(time())));
}

# Make sure our URL ends with a slash.
my $base_url = &normalize_url($q, \&check_url);

print $q->header();

use vars qw($title);
$title = "Search for Seminars";

my $layout = 
    Technion::Seminars::Layout->new(
        'path' => $base_url,
        'title' => $title,
    );

my $o = Gamla::TextStream::Out::File->new(\*STDOUT);

sub draw_page
{
    my $o = shift;

    $o->print("<h1>$title</h1>\n");

    $o->print("This would be the daily calendar.");
}







$layout->render($o, \&draw_page);
