#!/usr/bin/perl -w

# This is meant to suppress these annoying "subroutine redefined" warnings
no warnings "redefine";

use strict;

use CGI;

use DBI;

use Gamla::TextStream::Out::File;

use Technion::Seminars::Config;
use Technion::Seminars::Layout;
use Technion::Seminars::SlashUrl;
use Technion::Seminars::UserMan;
use Technion::Seminars::TypeMan;
use Technion::Seminars::DBI;

use Technion::Seminars::MDDA::OneTable;


my $q = CGI->new();

sub check_url
{
    my $url = shift;

    my $verdict = ($url =~ /^admin\/clubs\/(\w+\/(((subjects\/(\w+\/)?)|(seminars\/([^\/]+\/))))?)?/) ? 1 : 0;
    
    return ($verdict, "admin/clubs/");
}

# Make sure our URL ends with a slash.
my $base_url = &normalize_url($q, \&check_url, "https");

my (%cookie);
my ($user, $password, $user_id);
my $admin_level = "readonly";

my $user_man = Technion::Seminars::UserMan->new();

if (%cookie = $q->cookie('seminars_auth'))
{
    ($user, $password) = $user_man->get_user_and_password($q);

    ($admin_level, $user_id) = $user_man->get_admin_level($user, $password);
}

print $q->header();

my $title = "Club Management";

my $base_url_wo_last_component = $base_url;
$base_url_wo_last_component =~ s/\/[^\/]*$//;

my $layout = 
    Technion::Seminars::Layout->new(
        'path' => $base_url_wo_last_component,
        'title' => $title,
        'admin_level' => $admin_level,
    );

my $o = Gamla::TextStream::Out::File->new(\*STDOUT);

my $draw_permissions_form = sub {
    my $o = shift;
    my $dbh = shift;
    my $club_id = shift;
    my $clubname = shift;

    $o->print("\n\n<h2>Editing $clubname" . "'s permissions</h2>\n\n");

    $o->print("<form method=\"post\" action=\"modify_permissions.cgi\">\n");
    $o->print("<table border=\"1\">\n");
    $o->print("<tr><td>User</td><td>None</td><td>Seminars Only</td><td>Subjects</td></tr>\n");

    my $sth = $dbh->prepare(
        "SELECT permissions.User_ID, users.Username, " . 
        "users.Name, permissions.Seminars, permissions.Subjects " . 
        "FROM users, permissions " . 
        "WHERE permissions.Club_ID = $club_id AND " . 
        "permissions.User_ID = users.User_ID AND users.Super_Admin = 0"
    );

    my $rv = $sth->execute();

    while (my $row = $sth->fetchrow_arrayref())
    {
        my ($user_id, $username, $name, $can_edit_seminars, $can_edit_subjects) = @$row;

        $o->print("<tr>\n");
        
        $o->print("<td><b>$name ($username)</b></td>\n");
        my @values = (0,0,0);
        if ($can_edit_seminars)
        {
            if ($can_edit_subjects)
            {
                $values[2] = 1;
            }
            else
            {
                $values[1] = 1;
            }
        }
        else
        {
            $values[0] = 1;
        }
        for my $i (0 .. 2)
        {
            $o->print("<td><input type=\"radio\" name=\"$user_id\" value=\"$i\" " . ($values[$i] ? "checked=\"1\"" : "") . " /></td>\n");
        }
        $o->print("</tr>\n");        
    }
    $o->print("</table>\n");

    $o->print("<br />\n<input type=\"submit\" value=\"Submit\" />\n");
    $o->print("</form>\n");

};

my $edit_subjects = sub {
    my $o = shift;
    my $dbh = shift;

    my $uc = shift;
    my @url_components = @$uc;

    my $club_id = shift;
    my $clubname = shift;

    if (scalar(@url_components) == 0)
    {

        $o->print("\n<h1>Editing Subjects</h1>\n");

        my $sth = $dbh->prepare(
            "SELECT Subject_ID, Name FROM subjects WHERE Club_ID = $club_id ORDER BY Name"
        );
        my $rv = $sth->execute();
        
        $o->print("<table>\n");
        while (my $row = $sth->fetchrow_arrayref())
        {
            $o->print("<form method=\"post\" action=\"modify_subject.cgi\">\n");
            $o->print("<tr><td><input name=\"name\" value=\"" . 
                CGI::escapeHTML($row->[1]) . 
                "\" /><input type=\"hidden\" name=\"id\" value=\"" . 
                $row->[0] . 
                "\" /></td><td><input type=\"submit\" value=\"Update\" /></tr>\n"
                );
            $o->print("</form>\n");
        }

        $o->print("<tr><td colspan=\"2\"><h2>Add New Subject<h2></td></tr>");
        $o->print("<form method=\"post\" action=\"add_subject.cgi\">\n");
        $o->print("<tr><td><input name=\"name\" value=\"\" />" .
            "</td><td><input type=\"submit\" value=\"Add\"></td></tr>\n"
            );
        $o->print("</form>\n");

        $o->print("</table>\n");

    }
    else
    {
        my $script = shift(@url_components);

        if ($script eq "modify_subject.cgi")
        {
            my $subject_id = $q->param("id");
            my $name = $q->param("name");

            my $sth = $dbh->prepare("UPDATE subjects SET Name=" . $dbh->quote($name) . " WHERE SubjecT_ID = $subject_id AND Club_ID = $club_id");

            my $rv = $sth->execute();

            $o->print("<h1>OK</h1>\n\n");

            $o->print("<p>The name was changed.</p>\n");            
        }
        elsif ($script eq "add_subject.cgi")
        {
            my $name = $q->param("name");

            my $sth = $dbh->prepare("INSERT INTO subjects (Subject_ID, Club_ID, Name) VALUES (0, $club_id, " . $dbh->quote($name) . ")");

            my $rv = $sth->execute();

            $o->print("<h1>OK</h1>\n\n");

            $o->print("<p>The subject was added.</p>\n");            
        }
    }    
};


my $draw_page = sub {
    my $o = shift;

    my $mdda = 
        Technion::Seminars::MDDA::OneTable->new(
            'clubs', 
            $config{'database'}->{'tables'}->{'clubs'}
        );
    

    if ($admin_level eq "readonly")
    {
        return;
    }

    my @url_components = split(/\//, $base_url);

    my $admin = shift(@url_components);
    my $clubs = shift(@url_components);
    
    if (scalar(@url_components) == 0)
    {
        # The root of the sub-site

        $o->print("<h1>Clubs Administration</h1>\n\n");

        my $dbh = Technion::Seminars::DBI->new();
        my ($sth, $rv, $data);

        if ($admin_level eq "site")
        {
            $o->print("<h2><a href=\"./new/\">Add a New Club</a></h2>\n");
            $o->print("<h2>Existing Clubs</h2>\n");
        }

        my ($query);

        if ($admin_level eq "site")
        {
            $query = "SELECT Clubname, Name FROM clubs ORDER BY clubs.Name";
        }
        else
        {
            $sth = $dbh->prepare("SELECT User_ID FROM users WHERE Username = " . $dbh->quote($user));
            $rv = $sth->execute();
            $data = $sth->fetchrow_arrayref();
            
            my $user_id = $data->[0];
            
            $query = "SELECT Clubs.Clubname, Clubs.Name FROM clubs, permissions WHERE ((clubs.Club_ID = permissions.Club_ID) AND (permissions.User_ID = $user_id)) ORDER BY clubs.Name";
        }
        $sth = $dbh->prepare($query);
        $rv = $sth->execute();
        while ($data = $sth->fetchrow_arrayref())
        {
            $o->print("<a href=\"./" . $data->[0] . "/\">" .
                CGI::escapeHTML($data->[1]) . 
                "</a><br />\n");                
        }
    }
    else
    {
        my $clubname = shift(@url_components);
        if ($clubname eq "new")
        {
            if ($admin_level eq "site")
            {
                if (scalar(@url_components) == 0)
                {
                    $o->print("<h1>Add a New Club</h1>\n\n");
                
                    $mdda->render_add_form($o);
                }
                else
                {
                    # Let's process the form request.
                    $mdda->perform_add_operation($q, $o, "The club was added");
                    
                }
            }
        }
        else
        {
            my $dbh = Technion::Seminars::DBI->new();
            my $sth = $dbh->prepare("SELECT Club_ID FROM clubs WHERE Clubname = '$clubname'");
            my $rv = $sth->execute();
            
            my $row = $sth->fetchrow_arrayref();
            if ($row)
            {
                my $club_id = $row->[0];
                
                my @club_permissions;
                
                if (($admin_level eq "site") || 
                    (eval { 
                        @club_permissions = $user_man->can_edit_club(
                            $user_id, 
                            $club_id
                            ) ; 
                        $club_permissions[0] 
                        }
                    ))
                {
                    my $can_edit_subjects = (($admin_level eq "site") || $club_permissions[1]);
                    
                    if (scalar(@url_components) == 0)
                    {
                        if ($can_edit_subjects)
                        {
                            $mdda->render_edit_form(
                                $o, 
                                "Club_ID", 
                                $club_id,
                                'field-title' => $clubname,
                            );

                            {
                                $o->print("\n\n<h2><a href=\"./subjects/\">Edit Subjects</a></h2>\n\n");
                            }
                        }

                        if ($admin_level eq "site")
                        {
                            $draw_permissions_form->(
                                $o,
                                $dbh,
                                $club_id,
                                $clubname,
                            );
                        }
                    }
                    else
                    {
                        my $script = shift(@url_components);

                        if ($script eq "edit.cgi")
                        {
                            $mdda->perform_edit_operation(
                                $q, $o,
                                "Club_ID",
                                'record-title' => "club",
                                'id-field-title' => "club ID",
                                'dependent-tables' => [ "permissions" ],
                            );
                        }
                        elsif ($script eq "modify_permissions.cgi")
                        {
                            if ($admin_level eq "site")
                            {
                                my @user_ids_list;

                                my $sth = $dbh->prepare(
                                    "SELECT permissions.User_ID " .
                                    "FROM users, permissions " .
                                    "WHERE permissions.Club_ID = $club_id " . 
                                        "AND permissions.User_ID = users.User_ID AND users.Super_Admin = 0"
                                );
                                my $rv = $sth->execute();

                                while (my $row = $sth->fetchrow_arrayref())
                                {
                                    push @user_ids_list, $row->[0];
                                }
                                foreach my $user_id (@user_ids_list)
                                {
                                    my $value = $q->param($user_id);
                                    if (!defined($value))
                                    {
                                        next;
                                    }

                                    my ($seminars, $subjects);
                                    
                                    ($seminars, $subjects) = (map { $_ ? 1 : 0 } (($value>=1), ($value>=2)));
                                    my $sth = $dbh->prepare("UPDATE permissions SET Seminars=$seminars, Subjects=$subjects WHERE User_ID = $user_id AND Club_ID = $club_id");

                                    my $rv = $sth->execute();
                                }

                                $o->print("\n\n<h1>OK - The Permissions Were Edited</h1>\n");
                            }
                        }
                        elsif ($script eq "subjects")
                        {
                            if ($can_edit_subjects)
                            {
                                $edit_subjects->(
                                    $o,
                                    $dbh,
                                    \@url_components,
                                    $club_id, $clubname,
                                );
                            }
                        }
                    }
                }
            }
            else
            {
            }
        }
    }
};

$layout->render($o, $draw_page);
