#!/usr/bin/perl -w

# This is meant to suppress these annoying "subroutine redefined" warnings
no warnings "redefine";

use strict;

use CGI;

use DBI;

use Technion::Seminars::Config;
use Technion::Seminars::Layout;
use Technion::Seminars::SlashUrl;
use Technion::Seminars::UserMan;

use Gamla::TextStream::Out::File;

my $q = CGI->new();

sub check_url
{
    my $url = shift;

    my $verdict = ($url =~ /^admin\/users\/([A-Za-z_]*\/)?$/) ? 1 : 0;
    
    return ($verdict, "admin/users/");
}

# Make sure our URL ends with a slash.
my $base_url = &normalize_url($q, \&check_url, "https");

my (%cookie);
my ($user, $password);
my $admin_level = "readonly";

my $user_man = Technion::Seminars::UserMan->new();

if (%cookie = $q->cookie('seminars_auth'))
{
    $user = $cookie{'user'};
    $password = $cookie{'password'};

    $admin_level = $user_man->get_admin_level($user, $password);
}

print $q->header();

my $title = "User Management";

my $layout = 
    Technion::Seminars::Layout->new(
        'path' => $base_url,
        'title' => $title,
        'admin_level' => $admin_level,
    );

my $o = Gamla::TextStream::Out::File->new(\*STDOUT);

my $draw_page = sub {
    my $o = shift;    
    
    $o->print("<h1>$title</h1>\n\n");
    
    if ($admin_level eq "site")
    {
        if ($base_url eq "admin/users/")
        {
            $o->print("<h2><a href=\"./new\">Add New User</a></h2>");
            $o->print("<h2>Existing Users</h2>\n");
            
            my $dbh = DBI->connect(@{$config{'database'}}{'dsn', 'user', 'password'});
            my $sth = $dbh->prepare("SELECT * FROM users");
            my $rv = $sth->execute();
            while (my $row = $sth->fetchrow_hashref())
            {
                $o->print("<p>\n<a href=\"./" . $row->{'Username'} . "/\">");
                $o->print($row->{'Username'} . " (" .$row->{'Name'} . ")</a>\n");
                $o->print("</p>\n\n");
            }
        }
        elsif ($base_url eq "admin/users/new/")
        {
        }
    }
};

$layout->render($o, $draw_page);
